sudo: required

language: c

services:
  - docker

script:
  - docker build --tag devel -f Dockerfile.dev .

before_deploy:
  - export DOCKERID=`docker ps -alq`
  - docker cp $DOCKERID:/source/BiobaseHTTPTools.tar.gz .

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "BiobaseHTTPTools.tar.gz"
  draft: true  
