sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - mkdir binaries
  - docker run -v binaries:/source/binaries -other -options devel "cp /source/BiobaseHTTPTools.tar.gz /source/binaries"


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "/binaries/BiobaseHTTPTools.tar.gz"
  draft: true  
