sudo: required

language: c

services:
  - docker

script:
  - docker build --tag devel -f Dockerfile.dev .

deploy:
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file: "BiobaseHTTPTools.tar.gz"
  draft: true  
