sudo: required

language: c

services:
  - docker

before_install:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - ./deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "BiobaseHTTPTools.tar.gz"
  draft: true  
