sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - docker create --name develcontainer devel
  - docker cp develcontainer:/source/BiobaseHTTPTools.tar.gz .  


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "$TRAVIS_BUILD_DIR/binaries/BiobaseHTTPTools.tar.gz"
  draft: true  
