sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - mkdir $TRAVIS_BUILD_DIR/binaries
  - echo $TRAVIS_BUILD_DIR
  - ls
  - docker run -v $TRAVIS_BUILD_DIR/binaries:/source/binaries devel 'cp /source/BiobaseHTTPTools.tar.gz /source/binaries'


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "$TRAVIS_BUILD_DIR/binaries/BiobaseHTTPTools.tar.gz"
  draft: true  
