sudo: required

language: c

services:
  - docker

script:
  - docker build --name devel -f Dockerfile.dev .

before_deploy:
  - docker cp devel:/source/BiobaseHTTPTools.tar.gz .

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "BiobaseHTTPTools.tar.gz"
  draft: true  
