FROM alpine:latest

RUN apk update
RUN apk add --no-cache musl musl-dev musl-utils musl-dbg ghc ghc-dev ghc-doc cabal zlib-dev zlib tar gzip wget

ADD . source
WORKDIR source

RUN mkdir BiobaseHTTPTools
RUN cabal sandbox init
RUN cabal update
RUN cabal install --bindir=BiobaseHTTPTools --ghc-options="-optl-static -optl-pthread -fPIC"
RUN tar -cvzf BiobaseHTTPTools.tar.gz BiobaseHTTPTools
